// WORKOUT — the OBSERVED heart-rate ceiling (TS-03).
//
// Not a physiological HRmax. This is the highest heart rate the band actually
// held on you, with the date it happened. If you have never gone truly hard it
// is an underestimate and it will keep creeping up — that is the honest shape
// of the number, and the copy must say "highest we've seen: 184, on 3 Aug",
// never "your max HR is 184", and must never invite a max-effort test.
//
// WHY THE HOLD GUARD IS THE WHOLE FEATURE. Every zone boundary in the app is a
// fraction of this number, so a single PPG artifact — one 210 bpm sample from a
// sleeve dragging across the optical window — would inflate the ceiling forever
// and silently drag every boundary up, with no way for the user to see why
// their easy runs stopped being easy. So a candidate counts only when it was
// HELD for [holdSeconds] continuous seconds AND the accelerometer says the body
// was moving while it happened. A held-but-still high HR is a stress response,
// a fever or an artifact, and it is not a ceiling.
//
// PER-DEVICE (device.dart contract). The motion gate is NOT universal: on our
// own captures the two families' resting accelerometer noise floors differ by
// ~4x (gen4 |‖a‖−1| median 0.034 g / p90 0.058 g over 672k rows; gen5+MG median
// 0.007–0.012 g / p90 0.018–0.024 g over 260k rows). One shared gate is either
// "moving" through half of a gen4 night or unreachable on a gen5 walk, and
// either way it is a fabricated corroboration. Unknown family REFUSES; it does
// not silently borrow gen4's floor.
//
// WHAT THE GUARD DOES NOT CATCH. Run over the real gen4 capture's own labelled
// sessions it trims 4-8 bpm off each session's raw maximum (a 193 bpm run peak
// becomes 189; a walk's 188 becomes 180) — so it removes single-sample spikes,
// which is what it is for. It does NOT remove CADENCE LOCK: a walk that reports
// 180 bpm for twenty seconds while the wrist is swinging satisfies both the
// hold and the motion test, because the artifact is generated BY the motion.
// That is why the number is labelled with its session and its date, so a wrong
// one is visible and attributable rather than an anonymous ceiling.
//
// SKIN TONE. Wrist reflectance PPG error at intensity is larger on darker skin
// (published bias up to ~11.8 bpm), and that bias rides straight into this
// number and into every zone built on it. Nothing here can correct it; the
// screen has to say it.

import 'dart:math' as math;

import '../device.dart';
import '../types.dart';
import '../util.dart';

/// A heart rate that was held long enough, while moving, to count.
class HrCeiling {
  /// The bpm that was met or exceeded for the whole hold.
  final double bpm;

  /// Start of the qualifying hold (epoch ms) — the "on 3 Aug" in the copy.
  final double tsMs;

  /// How long the hold actually ran (>= the required hold).
  final int heldSeconds;

  /// Mean |‖a‖ − 1| in g over the hold — the corroborating motion.
  final double motionG;

  const HrCeiling({
    required this.bpm,
    required this.tsMs,
    required this.heldSeconds,
    required this.motionG,
  });

  Map<String, dynamic> toJson() => {
        'bpm': round6(bpm),
        'ts_ms': tsMs,
        'held_seconds': heldSeconds,
        'motion_g': round6(motionG),
      };
}

/// Mean resting-motion floor per family, in g of |‖a‖ − 1|, measured on our own
/// captures (see the header). The gate sits above each family's own p90 and
/// well below its p99, so ordinary wear does not corroborate and real movement
/// does.
///
/// PUBLIC because a caller that wants to explain the refusal has to ask the
/// same question this metric asks — "is there a gate for this stamp" — and
/// there is no longer a global list of known families to ask instead. Read it
/// through [calibrationFor]; it is this metric's table and nothing else's.
const Map<String, double> hrCeilingMotionGateG = {
  'gen4': 0.10,
  'gen5': 0.04,
};

/// Above this, a HELD heart rate is a sensor fault rather than a heart — no
/// per-family split, this is a physiological bound and not a sensor property.
const double _absurdBpm = 240.0;

/// The highest heart rate held for [holdSeconds] continuous seconds with
/// corroborating motion, over one session's co-sampled 1 Hz streams.
///
/// [hr] and [accel] must be the SAME session and index-aligned (sample i of one
/// is sample i of the other), exactly as the pipeline emits them; they are
/// sorted together here, so caller order does not matter but pairing does.
/// [deviceFamily] is the ingest-stamped id — NULL (every pre-schema-41 row,
/// every import, every raw replay) is a refusal, not gen4.
///
/// Returns ABSENT when the session simply contains no qualifying hold. That is
/// the common case and it is correct: most sessions do not test your ceiling.
/// The app-wide ceiling is the max over sessions of the present values, which
/// is the caller's one-line reduce — deliberately not a function here, so that
/// the guard cannot be bypassed by feeding it un-guarded numbers.
Metric<HrCeiling> sessionHrCeiling(
  List<HrSample> hr,
  List<AccelSample> accel, {
  String? deviceFamily,
  int holdSeconds = 15,
  double maxGapSeconds = 2.0,
}) {
  const inputs = ['hr_1hz', 'accel_1hz', 'device_family'];
  final gate = calibrationFor(hrCeilingMotionGateG, deviceFamily);
  if (gate == null) {
    return Metric<HrCeiling>.absent(
      tier: Tier.high,
      inputs_used: inputs,
      note: unknownFamilyNote(deviceFamily),
    );
  }
  if (accel.length != hr.length) {
    return const Metric<HrCeiling>.absent(
      tier: Tier.high,
      inputs_used: inputs,
      note: 'hr and accel must be index-aligned samples of one session',
    );
  }

  // Pair, drop unusable samples, sort by time. A sample with no HR or no accel
  // can neither set a ceiling nor corroborate one.
  final rows = <({double ts, double hr, double motion})>[];
  for (var i = 0; i < hr.length; i++) {
    final h = hr[i];
    final a = accel[i];
    if (!h.valid || !a.valid) continue;
    if (h.hr >= _absurdBpm) continue;
    final mag = math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z);
    rows.add((ts: h.tsMs, hr: h.hr, motion: (mag - 1.0).abs()));
  }
  rows.sort((a, b) => a.ts.compareTo(b.ts));

  final holdMs = holdSeconds * 1000.0;
  final gapMs = maxGapSeconds * 1000.0;
  // A real held effort's corroborating motion is not necessarily even across
  // the hold (e.g. a couple of seconds of arm swing at each end of a quiet
  // middle), so corroboration is judged on a short trailing sub-window, not
  // the whole hold's average — a real burst anywhere in the hold would get
  // diluted back below the gate by an otherwise-quiet average, which is
  // exactly the edges-quiet-middle case this exists for. As the window
  // extends past the minimal holdSeconds, that trailing sub-window sweeps
  // across the rest of the candidate span, so a burst anywhere in it still
  // gets found — capped, so one quiet start can't turn this into an O(n²)
  // scan of a whole day.
  final maxSpanMs = holdMs * 4;
  const corrobMs = 3000.0; // "a couple of seconds of arm swing"
  HrCeiling? best;
  // ponytail: O(n · holdSeconds) — one session at 1 Hz, so a bounded number of
  // passes over a few thousand samples. A monotonic-deque sliding minimum if
  // it ever runs over a whole day.
  for (var i = 0; i < rows.length; i++) {
    var lo = rows[i].hr;
    var motionSum = 0.0;
    var count = 0;
    var trailStart = i;
    var trailSum = 0.0;
    var trailCount = 0;
    // Running max of the trailing sub-window average seen so far as j sweeps
    // forward. trailStart only ever advances, so once j moves past a burst
    // the trailing sum itself forgets it — bestTrail is what keeps a burst
    // near the start of a long hold (or anywhere before a quiet tail) from
    // being lost once the window slides past it.
    var bestTrail = 0.0;
    for (var j = i; j < rows.length; j++) {
      if (j > i && rows[j].ts - rows[j - 1].ts > gapMs) break; // stream broke
      lo = math.min(lo, rows[j].hr);
      motionSum += rows[j].motion;
      count++;
      trailSum += rows[j].motion;
      trailCount++;
      while (rows[j].ts - rows[trailStart].ts > corrobMs) {
        trailSum -= rows[trailStart].motion;
        trailCount--;
        trailStart++;
      }
      // Only trust the trailing average once it actually spans a full
      // corrobMs — before that (the first couple of samples at a fresh
      // start index) it's one or two samples, and a single noisy sample
      // could otherwise "corroborate" as if it were a real sustained burst.
      final trailAvg = trailSum / trailCount;
      if (rows[j].ts - rows[i].ts >= corrobMs && trailAvg > bestTrail) {
        bestTrail = trailAvg;
      }
      final span = rows[j].ts - rows[i].ts;
      if (span < holdMs) continue;
      if (span > maxSpanMs) break; // gave this start its fair shot
      // The window qualifies on duration. `lo` is the bpm sustained across
      // all of it. Only stop once a short burst of real motion actually
      // corroborated it ANYWHERE in the span so far (bestTrail), not just in
      // whatever the trailing window currently covers.
      if (bestTrail >= gate) {
        if (best == null || lo > best.bpm) {
          best = HrCeiling(
            bpm: lo,
            tsMs: rows[i].ts,
            heldSeconds: (span / 1000).round(),
            motionG: motionSum / count,
          );
        }
        break;
      }
    }
  }

  if (best == null) {
    return Metric<HrCeiling>.absent(
      tier: Tier.high,
      inputs_used: inputs,
      note: 'no_held_ceiling:hold=${holdSeconds}s,motion_gate_g=$gate',
    );
  }
  return Metric<HrCeiling>(
    value: best,
    confidence: (best.heldSeconds / (holdSeconds * 2.0)).clamp(0.3, 0.8),
    tier: Tier.high,
    inputs_used: inputs,
    note: 'OBSERVED ceiling, not physiological HRmax — an underestimate if you '
        'have never gone truly hard, and it will keep creeping up. Label it '
        'with its date. Wrist PPG at intensity is biased by skin tone '
        '(published up to ~11.8 bpm) and that rides into every zone built on '
        'this number.',
  );
}
