"""Regenerate icons.js from Phosphor Icons (MIT): python3 tools/build_icons.py <phosphor assets dir>

The assets dir is `package/assets` from `npm pack @phosphor-icons/core`. Icons
are kept as inline SVG paths (vector, sharp at any size), in four weights.
"""
import json
import os
import re
import sys

# DataStrap name -> Phosphor name
NAMES = {
    'activity': 'pulse', 'audio-waveform': 'waveform', 'battery-charging': 'battery-charging', 'bed': 'bed',
    'bike': 'bicycle', 'brain': 'brain', 'calendar': 'calendar-blank', 'chevron-left': 'caret-left',
    'chevron-right': 'caret-right', 'clock': 'clock', 'droplet': 'drop', 'dumbbell': 'barbell', 'flame': 'flame',
    'footprints': 'footprints', 'gauge': 'gauge', 'heart-pulse': 'heartbeat', 'heart': 'heart', 'medal': 'medal',
    'moon': 'moon-stars', 'mountain': 'mountains', 'person-standing': 'person', 'sparkles': 'sparkle', 'star': 'star',
    'sun': 'sun', 'sunrise': 'sun-horizon', 'thermometer': 'thermometer', 'timer': 'timer', 'trending-down': 'trend-down',
    'trending-up': 'trend-up', 'trophy': 'trophy', 'volleyball': 'soccer-ball', 'wind': 'wind', 'zap': 'lightning',
    'waves': 'waves', 'house': 'house', 'hourglass': 'hourglass-medium', 'refresh': 'arrows-clockwise',
    'run': 'person-simple-run', 'ping-pong': 'ping-pong', 'swim': 'swimming-pool',
}
WEIGHTS = {'regular': '', 'duotone': '-duotone', 'fill': '-fill', 'bold': '-bold'}

assets = sys.argv[1]
out = {w: {} for w in WEIGHTS}
for ours, theirs in NAMES.items():
    for weight, suffix in WEIGHTS.items():
        with open(os.path.join(assets, weight, f'{theirs}{suffix}.svg')) as fh:
            svg = fh.read()
        out[weight][ours] = re.sub(r'^<svg[^>]*>|</svg>\s*$', '', svg.strip())

js = f"""// Icons from Phosphor Icons (https://phosphoricons.com), MIT License.
// Copyright (c) 2023 Phosphor Icons. Generated by tools/build_icons.py; don't edit by hand.
// Each entry is the inner markup of a 256x256 filled SVG, in four weights.
const PHOSPHOR = {json.dumps(out, ensure_ascii=False, indent=0)};

// ph('heart', 'cls', 'duotone') -> inline SVG (vector, sharp at any size).
function ph(name, cls = '', weight = 'regular') {{
  const set = PHOSPHOR[weight] || PHOSPHOR.regular;
  const body = set[name] || PHOSPHOR.regular[name] || PHOSPHOR.regular.activity;
  return `<svg class="ph ${{cls}}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true" focusable="false">${{body}}</svg>`;
}}
"""
with open(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'icons.js'), 'w') as fh:
    fh.write(js)
print(f'icons.js: {len(NAMES)} icons x {len(WEIGHTS)} weights')
